# Site settings
author: Daniel Carvalho
title: Cannot Load File
header-img: img/home-bg.png
email: danielcarvalhovr@gmail.com
copyright_name: Daniel Carvalho
description: > # this means to ignore newlines until "baseurl:"
  The Code Monkey
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  dan-dc25

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
